---
title: "Predicting Molecular Properties"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---

# 1. Initialise 

```{r}
library(readr)
library(tidyverse)
library(forcats)
library(ggplot2)
library(ggcorrplot)
```
# 2. Import Data

```{r,results="hide"}

train <- read_csv("C:/Users/NSAWLE/OneDrive - The University of Melbourne/Desktop/Molecule/train_.csv")

View(train)

```
# Inspect Data

```{r}
head(train)
```
```{r}
summary(train)
```
```{r}
# Removing ID column as it does not add any value to the data
train$id <- NULL 

View(train)

 ggplot(train,aes(train$type))+ geom_bar(fill = "#0073C2FF") + labs(title="Distribution of molecule types", x="Molecule Type")

```
```{r}
  ggplot(train,aes(x=train$type,y=train$atom_index_0))+ geom_boxplot(fill = "skyblue") + labs(title="Distribution of molecule types", x="Molecule Type", y="Atom Index 0")
```

```{r}
  ggplot(train,aes(x=train$type,y=train$atom_index_1))+ geom_boxplot(fill = "skyblue") + labs(title="Distribution of molecule types", x="Molecule Type", y="Atom Index 1")
```
```{r}

# There is a positive correlation between atom index 0 and scalar coupling and 
# negative correlation between atom index 1 and scalar coupling

corr <- subset(train,select=c(2,3,5))
corr <- round(cor(corr), 1)
head(corr[, 1:3])
ggcorrplot(corr,colors = c("#6D9EC1", "white", "#E46726"))


```







